# Generated by Django 4.1.2 on 2022-10-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(default='admin@default.com', max_length=40)),
                ('langage_habituel', models.CharField(max_length=30)),
                ('annee_de_naissance', models.DateField()),
                ('numero_employee', models.CharField(max_length=10)),
                ('emplacement', models.CharField(max_length=30)),
            ],
        ),
    ]
