# Generated by Django 4.1.2 on 2022-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(default='admin@default.com', max_length=40)),
                ('langage_habituel', models.CharField(max_length=30)),
                ('annee_de_naissance', models.DateField()),
                ('numero_employee', models.CharField(max_length=10)),
                ('emplacement', models.CharField(max_length=30)),
                ('statut', models.CharField(default='Etudiante', max_length=30)),
                ('commentaire_sur_savoir_faire', models.CharField(default='je sais cuisiner', max_length=200)),
                ('votre_cv', models.FileField(default='file', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='nous_contacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='admin@default.com', max_length=40)),
                ('titre', models.CharField(max_length=30)),
                ('laisser_un_message', models.CharField(default='votre besoin', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(default='admin@default.com', max_length=40)),
                ('telephone_principale', models.CharField(default='73693576', max_length=8)),
                ('telephone_secondaire', models.CharField(max_length=8, null=True)),
                ('emplacement', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=40)),
                ('langage_habituel', models.CharField(max_length=30)),
                ('service_choisis', models.CharField(max_length=50)),
                ('moment', models.CharField(choices=[('1', '30 minute- 1heure'), ('2', '1heure- 2heure'), ('3', '3heure- 4heure'), ('4', 'peu importe')], default='30 minute- 1heure', max_length=100, unique=True)),
            ],
        ),
    ]
