# Generated by Django 4.1.2 on 2022-11-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='emplacement',
        ),
    ]
