# Generated by Django 4.1.2 on 2022-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=30),
        ),
    ]
