# Generated by Django 4.1.2 on 2022-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0002_alter_employee_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commentaire_sur_savoir_faire',
            field=models.CharField(default='je sais cuisiner', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='statut',
            field=models.CharField(default='Etudiante', max_length=30),
        ),
    ]
