# Generated by Django 4.1.2 on 2022-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0002_remove_service_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='emplacement',
            field=models.CharField(default='12OO logement', max_length=30),
        ),
    ]
