# Generated by Django 4.1.2 on 2022-11-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0003_service_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='moment_pour_vous_contacter',
            field=models.CharField(choices=[('1', '30 minute- 1heure'), ('2', '1heure- 2heure'), ('3', '3heure- 4heure'), ('4', 'peu importe')], default='30 minute- 1heure', max_length=100),
        ),
    ]
