# Generated by Django 4.1.2 on 2022-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0003_employee_commentaire_sur_savoir_faire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(default='admin@default.com', max_length=40)),
                ('telephone_pricipale', models.CharField(max_length=8)),
                ('telephone_secondaire', models.CharField(max_length=8)),
                ('emplacement', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=40)),
                ('langage_habituel', models.CharField(max_length=30)),
                ('service_choisis', models.CharField(max_length=50)),
            ],
        ),
    ]
