# Generated by Django 4.1.2 on 2022-10-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0005_rename_telephone_pricipale_service_telephone_principale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='telephone_principale',
        ),
    ]
