# Generated by Django 4.1.2 on 2022-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0006_remove_service_telephone_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='telephone_principale',
            field=models.CharField(default='73693576', max_length=8),
        ),
    ]
