# Generated by Django 4.1.2 on 2022-10-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0007_service_telephone_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='telephone_secondaire',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
