# Generated by Django 4.1.2 on 2022-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0008_alter_service_telephone_secondaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='nous_contacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='admin@default.com', max_length=40)),
                ('titre', models.CharField(max_length=30)),
                ('laisser_un_message', models.CharField(default='votre besoin', max_length=1000)),
            ],
        ),
    ]
