# Generated by Django 4.1.2 on 2022-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0009_nous_contacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='votre_cv',
            field=models.FileField(default='file', upload_to=''),
        ),
    ]
