# Generated by Django 4.1.2 on 2022-11-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulls', '0010_employee_votre_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='votre_cv',
            field=models.FileField(default='file', upload_to='uploads_files/'),
        ),
    ]
